/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * utoipa-axum
 * Utoipa's axum bindings for seamless integration for the two
 * OpenAPI spec version: 0.2.0
 */
export interface CollectionItem {
  added_at: string;
  collection: string;
  media_type: string;
  /** @nullable */
  poster_path?: string | null;
  title: string;
  tmdb_id: number;
}

export interface CollectionRequest {
  collection: string;
  media_type: string;
  /** @nullable */
  poster_path?: string | null;
  title: string;
  tmdb_id: number;
}

export interface CollectionStatus {
  in_collection: boolean;
}

export interface Download {
  /** @nullable */
  completed_at?: string | null;
  created_at: string;
  downloaded_bytes: number;
  episode: number;
  /** @nullable */
  error?: string | null;
  file_idx: number;
  file_path: string;
  id: number;
  info_hash: string;
  media_type: string;
  /** @nullable */
  poster_path?: string | null;
  /** @nullable */
  resolution?: string | null;
  season: number;
  status: string;
  title: string;
  tmdb_id: number;
  /** @nullable */
  total_bytes?: number | null;
}

export interface EnqueueDownloadRequest {
  episode?: number;
  /** @nullable */
  file_idx?: number | null;
  /** @nullable */
  info_hash?: string | null;
  media_type: string;
  /** @nullable */
  poster_path?: string | null;
  resolution: string;
  season?: number;
  title: string;
  tmdb_id: number;
}

export interface Episode {
  episode_number: number;
  name: string;
  /** @nullable */
  overview?: string | null;
  stills: string[];
}

export interface Genre {
  id: number;
  name: string;
}

export type MediaType = typeof MediaType[keyof typeof MediaType];


export const MediaType = {
  movie: 'movie',
  tv: 'tv',
} as const;

export interface Season {
  /** @nullable */
  air_date?: string | null;
  episode_count: number;
  episodes: Episode[];
  id: number;
  name: string;
  /** @nullable */
  poster_path?: string | null;
  season_number: number;
}

export interface Video {
  key: string;
  name: string;
  site: string;
  video_type: string;
}

export interface MediaItem {
  backdrops: string[];
  genres: Genre[];
  id: number;
  /** @nullable */
  imdb_id?: string | null;
  /** @nullable */
  logo_path?: string | null;
  media_type: MediaType;
  /** @nullable */
  overview?: string | null;
  /** @nullable */
  poster_path?: string | null;
  /** @nullable */
  rating?: number | null;
  /** @nullable */
  release_date?: string | null;
  /** @nullable */
  runtime?: number | null;
  /** @nullable */
  seasons?: Season[] | null;
  /** @nullable */
  tagline?: string | null;
  title: string;
  videos: Video[];
}

export interface RecordWatchRequest {
  /** @nullable */
  duration?: number | null;
  /** @nullable */
  episode?: number | null;
  /** @nullable */
  file_idx?: number | null;
  /** @nullable */
  info_hash?: string | null;
  media_type: string;
  /** @nullable */
  poster_path?: string | null;
  /** @nullable */
  progress?: number | null;
  /** @nullable */
  season?: number | null;
  title: string;
  tmdb_id: number;
}

export interface ResolutionEstimate {
  resolution: string;
  /**
     * @minimum 0
     * @nullable
     */
  size_bytes?: number | null;
  /** @nullable */
  size_display?: string | null;
  /** @minimum 0 */
  streams_count: number;
}

export interface SearchResult {
  /** @nullable */
  backdrop_path?: string | null;
  id: number;
  media_type: MediaType;
  /** @nullable */
  overview?: string | null;
  /** @nullable */
  poster_path?: string | null;
  /** @nullable */
  release_date?: string | null;
  title: string;
}

export interface StartStreamResponse {
  local: boolean;
  url: string;
}

export interface Stream {
  /** @nullable */
  audio?: string | null;
  /** @nullable */
  codec?: string | null;
  file_idx: number;
  hdr: boolean;
  imax: boolean;
  info_hash: string;
  name: string;
  /** @nullable */
  resolution?: string | null;
  score: number;
  /**
     * @minimum 0
     * @nullable
     */
  seeders?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  size_bytes?: number | null;
  /** @nullable */
  size_display?: string | null;
  source: string;
  /** @nullable */
  source_type?: string | null;
  title: string;
}

export interface SubtitleCue {
  /** End time in seconds */
  end: number;
  /** Start time in seconds */
  start: number;
  text: string;
}

export interface SubtitleTrack {
  id: string;
  language: string;
  /** Higher score = more likely to be in sync */
  score: number;
  url: string;
}

export interface WatchHistoryItem {
  duration: number;
  episode: number;
  file_idx: number;
  /** @nullable */
  info_hash?: string | null;
  last_watched: string;
  media_type: string;
  /** @nullable */
  poster_path?: string | null;
  progress: number;
  season: number;
  title: string;
  tmdb_id: number;
}

export type SearchParams = {
q: string;
};

export type SubtitleCuesParams = {
/**
 * URL of the SRT subtitle file
 */
url: string;
};

export type addToCollectionResponse204 = {
  data: void
  status: 204
}

export type addToCollectionResponseSuccess = (addToCollectionResponse204) & {
  headers: Headers;
};
;

export type addToCollectionResponse = (addToCollectionResponseSuccess)

export const getAddToCollectionUrl = () => {




  return `/cinema/api/collection`
}

export const addToCollection = async (collectionRequest: CollectionRequest, options?: RequestInit): Promise<addToCollectionResponse> => {

  const res = await fetch(getAddToCollectionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      collectionRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: addToCollectionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as addToCollectionResponse
}



export type getCollectionResponse200 = {
  data: CollectionItem[]
  status: 200
}

export type getCollectionResponseSuccess = (getCollectionResponse200) & {
  headers: Headers;
};
;

export type getCollectionResponse = (getCollectionResponseSuccess)

export const getGetCollectionUrl = (collection: string,) => {




  return `/cinema/api/collection/${collection}`
}

export const getCollection = async (collection: string, options?: RequestInit): Promise<getCollectionResponse> => {

  const res = await fetch(getGetCollectionUrl(collection),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getCollectionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCollectionResponse
}



export type isInCollectionResponse200 = {
  data: CollectionStatus
  status: 200
}

export type isInCollectionResponseSuccess = (isInCollectionResponse200) & {
  headers: Headers;
};
;

export type isInCollectionResponse = (isInCollectionResponseSuccess)

export const getIsInCollectionUrl = (collection: string,
    type: string,
    id: number,) => {




  return `/cinema/api/collection/${collection}/${type}/${id}`
}

export const isInCollection = async (collection: string,
    type: string,
    id: number, options?: RequestInit): Promise<isInCollectionResponse> => {

  const res = await fetch(getIsInCollectionUrl(collection,type,id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: isInCollectionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as isInCollectionResponse
}



export type removeFromCollectionResponse204 = {
  data: void
  status: 204
}

export type removeFromCollectionResponseSuccess = (removeFromCollectionResponse204) & {
  headers: Headers;
};
;

export type removeFromCollectionResponse = (removeFromCollectionResponseSuccess)

export const getRemoveFromCollectionUrl = (collection: string,
    type: string,
    id: number,) => {




  return `/cinema/api/collection/${collection}/${type}/${id}`
}

export const removeFromCollection = async (collection: string,
    type: string,
    id: number, options?: RequestInit): Promise<removeFromCollectionResponse> => {

  const res = await fetch(getRemoveFromCollectionUrl(collection,type,id),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: removeFromCollectionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as removeFromCollectionResponse
}



export type listDownloadsResponse200 = {
  data: Download[]
  status: 200
}

export type listDownloadsResponseSuccess = (listDownloadsResponse200) & {
  headers: Headers;
};
;

export type listDownloadsResponse = (listDownloadsResponseSuccess)

export const getListDownloadsUrl = () => {




  return `/cinema/api/downloads`
}

export const listDownloads = async ( options?: RequestInit): Promise<listDownloadsResponse> => {

  const res = await fetch(getListDownloadsUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listDownloadsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listDownloadsResponse
}



export type enqueueDownloadResponse204 = {
  data: void
  status: 204
}

export type enqueueDownloadResponseSuccess = (enqueueDownloadResponse204) & {
  headers: Headers;
};
;

export type enqueueDownloadResponse = (enqueueDownloadResponseSuccess)

export const getEnqueueDownloadUrl = () => {




  return `/cinema/api/downloads`
}

export const enqueueDownload = async (enqueueDownloadRequest: EnqueueDownloadRequest, options?: RequestInit): Promise<enqueueDownloadResponse> => {

  const res = await fetch(getEnqueueDownloadUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      enqueueDownloadRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: enqueueDownloadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as enqueueDownloadResponse
}



export type estimateDownloadResponse200 = {
  data: ResolutionEstimate[]
  status: 200
}

export type estimateDownloadResponseSuccess = (estimateDownloadResponse200) & {
  headers: Headers;
};
;

export type estimateDownloadResponse = (estimateDownloadResponseSuccess)

export const getEstimateDownloadUrl = (mediaType: string,
    tmdbId: number,) => {




  return `/cinema/api/downloads/estimate/${mediaType}/${tmdbId}`
}

export const estimateDownload = async (mediaType: string,
    tmdbId: number, options?: RequestInit): Promise<estimateDownloadResponse> => {

  const res = await fetch(getEstimateDownloadUrl(mediaType,tmdbId),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: estimateDownloadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as estimateDownloadResponse
}



export type deleteDownloadResponse204 = {
  data: void
  status: 204
}

export type deleteDownloadResponseSuccess = (deleteDownloadResponse204) & {
  headers: Headers;
};
;

export type deleteDownloadResponse = (deleteDownloadResponseSuccess)

export const getDeleteDownloadUrl = (id: number,) => {




  return `/cinema/api/downloads/${id}`
}

export const deleteDownload = async (id: number, options?: RequestInit): Promise<deleteDownloadResponse> => {

  const res = await fetch(getDeleteDownloadUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteDownloadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteDownloadResponse
}



export type movieDetailsResponse200 = {
  data: MediaItem
  status: 200
}

export type movieDetailsResponseSuccess = (movieDetailsResponse200) & {
  headers: Headers;
};
;

export type movieDetailsResponse = (movieDetailsResponseSuccess)

export const getMovieDetailsUrl = (id: number,) => {




  return `/cinema/api/movie/${id}`
}

export const movieDetails = async (id: number, options?: RequestInit): Promise<movieDetailsResponse> => {

  const res = await fetch(getMovieDetailsUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: movieDetailsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as movieDetailsResponse
}



export type searchResponse200 = {
  data: SearchResult[]
  status: 200
}

export type searchResponseSuccess = (searchResponse200) & {
  headers: Headers;
};
;

export type searchResponse = (searchResponseSuccess)

export const getSearchUrl = (params: SearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/cinema/api/search?${stringifiedParams}` : `/cinema/api/search`
}

export const search = async (params: SearchParams, options?: RequestInit): Promise<searchResponse> => {

  const res = await fetch(getSearchUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: searchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchResponse
}



export type similarResponse200 = {
  data: SearchResult[]
  status: 200
}

export type similarResponseSuccess = (similarResponse200) & {
  headers: Headers;
};
;

export type similarResponse = (similarResponseSuccess)

export const getSimilarUrl = (type: string,
    id: number,) => {




  return `/cinema/api/similar/${type}/${id}`
}

export const similar = async (type: string,
    id: number, options?: RequestInit): Promise<similarResponse> => {

  const res = await fetch(getSimilarUrl(type,id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: similarResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as similarResponse
}



export type movieStreamsResponse200 = {
  data: Stream[]
  status: 200
}

export type movieStreamsResponseSuccess = (movieStreamsResponse200) & {
  headers: Headers;
};
;

export type movieStreamsResponse = (movieStreamsResponseSuccess)

export const getMovieStreamsUrl = (id: number,) => {




  return `/cinema/api/streams/movie/${id}`
}

export const movieStreams = async (id: number, options?: RequestInit): Promise<movieStreamsResponse> => {

  const res = await fetch(getMovieStreamsUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: movieStreamsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as movieStreamsResponse
}



export type startStreamResponse200 = {
  data: StartStreamResponse
  status: 200
}

export type startStreamResponseSuccess = (startStreamResponse200) & {
  headers: Headers;
};
;

export type startStreamResponse = (startStreamResponseSuccess)

export const getStartStreamUrl = (infoHash: string,
    fileIdx: number,) => {




  return `/cinema/api/streams/start/${infoHash}/${fileIdx}`
}

export const startStream = async (infoHash: string,
    fileIdx: number, options?: RequestInit): Promise<startStreamResponse> => {

  const res = await fetch(getStartStreamUrl(infoHash,fileIdx),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: startStreamResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as startStreamResponse
}



export type tvStreamsResponse200 = {
  data: Stream[]
  status: 200
}

export type tvStreamsResponseSuccess = (tvStreamsResponse200) & {
  headers: Headers;
};
;

export type tvStreamsResponse = (tvStreamsResponseSuccess)

export const getTvStreamsUrl = (id: number,
    season: number,
    episode: number,) => {




  return `/cinema/api/streams/tv/${id}/${season}/${episode}`
}

export const tvStreams = async (id: number,
    season: number,
    episode: number, options?: RequestInit): Promise<tvStreamsResponse> => {

  const res = await fetch(getTvStreamsUrl(id,season,episode),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: tvStreamsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as tvStreamsResponse
}



export type subtitleCuesResponse200 = {
  data: SubtitleCue[]
  status: 200
}

export type subtitleCuesResponseSuccess = (subtitleCuesResponse200) & {
  headers: Headers;
};
;

export type subtitleCuesResponse = (subtitleCuesResponseSuccess)

export const getSubtitleCuesUrl = (params: SubtitleCuesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/cinema/api/subtitles/cues?${stringifiedParams}` : `/cinema/api/subtitles/cues`
}

export const subtitleCues = async (params: SubtitleCuesParams, options?: RequestInit): Promise<subtitleCuesResponse> => {

  const res = await fetch(getSubtitleCuesUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: subtitleCuesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as subtitleCuesResponse
}



export type movieSubtitlesResponse200 = {
  data: SubtitleTrack[]
  status: 200
}

export type movieSubtitlesResponseSuccess = (movieSubtitlesResponse200) & {
  headers: Headers;
};
;

export type movieSubtitlesResponse = (movieSubtitlesResponseSuccess)

export const getMovieSubtitlesUrl = (id: number,) => {




  return `/cinema/api/subtitles/movie/${id}`
}

export const movieSubtitles = async (id: number, options?: RequestInit): Promise<movieSubtitlesResponse> => {

  const res = await fetch(getMovieSubtitlesUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: movieSubtitlesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as movieSubtitlesResponse
}



export type tvSubtitlesResponse200 = {
  data: SubtitleTrack[]
  status: 200
}

export type tvSubtitlesResponseSuccess = (tvSubtitlesResponse200) & {
  headers: Headers;
};
;

export type tvSubtitlesResponse = (tvSubtitlesResponseSuccess)

export const getTvSubtitlesUrl = (id: number,
    season: number,
    episode: number,) => {




  return `/cinema/api/subtitles/tv/${id}/${season}/${episode}`
}

export const tvSubtitles = async (id: number,
    season: number,
    episode: number, options?: RequestInit): Promise<tvSubtitlesResponse> => {

  const res = await fetch(getTvSubtitlesUrl(id,season,episode),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: tvSubtitlesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as tvSubtitlesResponse
}



export type trendingResponse200 = {
  data: SearchResult[]
  status: 200
}

export type trendingResponseSuccess = (trendingResponse200) & {
  headers: Headers;
};
;

export type trendingResponse = (trendingResponseSuccess)

export const getTrendingUrl = () => {




  return `/cinema/api/trending`
}

export const trending = async ( options?: RequestInit): Promise<trendingResponse> => {

  const res = await fetch(getTrendingUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: trendingResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as trendingResponse
}



export type tvDetailsResponse200 = {
  data: MediaItem
  status: 200
}

export type tvDetailsResponseSuccess = (tvDetailsResponse200) & {
  headers: Headers;
};
;

export type tvDetailsResponse = (tvDetailsResponseSuccess)

export const getTvDetailsUrl = (id: number,) => {




  return `/cinema/api/tv/${id}`
}

export const tvDetails = async (id: number, options?: RequestInit): Promise<tvDetailsResponse> => {

  const res = await fetch(getTvDetailsUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: tvDetailsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as tvDetailsResponse
}



export type recordWatchResponse204 = {
  data: void
  status: 204
}

export type recordWatchResponseSuccess = (recordWatchResponse204) & {
  headers: Headers;
};
;

export type recordWatchResponse = (recordWatchResponseSuccess)

export const getRecordWatchUrl = () => {




  return `/cinema/api/watch`
}

export const recordWatch = async (recordWatchRequest: RecordWatchRequest, options?: RequestInit): Promise<recordWatchResponse> => {

  const res = await fetch(getRecordWatchUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      recordWatchRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: recordWatchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as recordWatchResponse
}



export type watchHistoryResponse200 = {
  data: WatchHistoryItem[]
  status: 200
}

export type watchHistoryResponseSuccess = (watchHistoryResponse200) & {
  headers: Headers;
};
;

export type watchHistoryResponse = (watchHistoryResponseSuccess)

export const getWatchHistoryUrl = () => {




  return `/cinema/api/watch/history`
}

export const watchHistory = async ( options?: RequestInit): Promise<watchHistoryResponse> => {

  const res = await fetch(getWatchHistoryUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: watchHistoryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as watchHistoryResponse
}
