/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * utoipa-axum
 * Utoipa's axum bindings for seamless integration for the two
 * OpenAPI spec version: 0.2.0
 */
export interface Episode {
  episode_number: number;
  name: string;
  /** @nullable */
  overview?: string | null;
  /** @nullable */
  still_path?: string | null;
}

export interface Genre {
  id: number;
  name: string;
}

export type MediaType = typeof MediaType[keyof typeof MediaType];


export const MediaType = {
  movie: 'movie',
  tv: 'tv',
} as const;

export interface Season {
  /** @nullable */
  air_date?: string | null;
  episode_count: number;
  episodes: Episode[];
  id: number;
  name: string;
  /** @nullable */
  poster_path?: string | null;
  season_number: number;
}

export interface Video {
  key: string;
  name: string;
  site: string;
  video_type: string;
}

export interface MediaItem {
  backdrops: string[];
  genres: Genre[];
  id: number;
  /** @nullable */
  imdb_id?: string | null;
  /** @nullable */
  logo_path?: string | null;
  media_type: MediaType;
  /** @nullable */
  overview?: string | null;
  /** @nullable */
  poster_path?: string | null;
  /** @nullable */
  rating?: number | null;
  /** @nullable */
  release_date?: string | null;
  /** @nullable */
  runtime?: number | null;
  /** @nullable */
  seasons?: Season[] | null;
  /** @nullable */
  tagline?: string | null;
  title: string;
  videos: Video[];
}

export interface SearchResult {
  /** @nullable */
  backdrop_path?: string | null;
  id: number;
  media_type: MediaType;
  /** @nullable */
  overview?: string | null;
  /** @nullable */
  poster_path?: string | null;
  /** @nullable */
  release_date?: string | null;
  title: string;
}

export interface StartStreamResponse {
  url: string;
}

export interface Stream {
  /** @nullable */
  audio?: string | null;
  /** @nullable */
  codec?: string | null;
  file_idx: number;
  hdr: boolean;
  imax: boolean;
  info_hash: string;
  name: string;
  /** @nullable */
  resolution?: string | null;
  score: number;
  /**
     * @minimum 0
     * @nullable
     */
  seeders?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  size_bytes?: number | null;
  /** @nullable */
  size_display?: string | null;
  source: string;
  /** @nullable */
  source_type?: string | null;
  title: string;
}

export interface SubtitleCue {
  /** End time in seconds */
  end: number;
  /** Start time in seconds */
  start: number;
  text: string;
}

export interface SubtitleTrack {
  id: string;
  language: string;
  /** Higher score = more likely to be in sync */
  score: number;
  url: string;
}

export type SearchParams = {
q: string;
};

export type SubtitleCuesParams = {
/**
 * URL of the SRT subtitle file
 */
url: string;
};

export type movieDetailsResponse200 = {
  data: MediaItem
  status: 200
}

export type movieDetailsResponseSuccess = (movieDetailsResponse200) & {
  headers: Headers;
};
;

export type movieDetailsResponse = (movieDetailsResponseSuccess)

export const getMovieDetailsUrl = (id: number,) => {




  return `/cinema/api/movie/${id}`
}

export const movieDetails = async (id: number, options?: RequestInit): Promise<movieDetailsResponse> => {

  const res = await fetch(getMovieDetailsUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: movieDetailsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as movieDetailsResponse
}



export type searchResponse200 = {
  data: SearchResult[]
  status: 200
}

export type searchResponseSuccess = (searchResponse200) & {
  headers: Headers;
};
;

export type searchResponse = (searchResponseSuccess)

export const getSearchUrl = (params: SearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/cinema/api/search?${stringifiedParams}` : `/cinema/api/search`
}

export const search = async (params: SearchParams, options?: RequestInit): Promise<searchResponse> => {

  const res = await fetch(getSearchUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: searchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchResponse
}



export type movieStreamsResponse200 = {
  data: Stream[]
  status: 200
}

export type movieStreamsResponseSuccess = (movieStreamsResponse200) & {
  headers: Headers;
};
;

export type movieStreamsResponse = (movieStreamsResponseSuccess)

export const getMovieStreamsUrl = (id: number,) => {




  return `/cinema/api/streams/movie/${id}`
}

export const movieStreams = async (id: number, options?: RequestInit): Promise<movieStreamsResponse> => {

  const res = await fetch(getMovieStreamsUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: movieStreamsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as movieStreamsResponse
}



export type startStreamResponse200 = {
  data: StartStreamResponse
  status: 200
}

export type startStreamResponseSuccess = (startStreamResponse200) & {
  headers: Headers;
};
;

export type startStreamResponse = (startStreamResponseSuccess)

export const getStartStreamUrl = (infoHash: string,
    fileIdx: number,) => {




  return `/cinema/api/streams/start/${infoHash}/${fileIdx}`
}

export const startStream = async (infoHash: string,
    fileIdx: number, options?: RequestInit): Promise<startStreamResponse> => {

  const res = await fetch(getStartStreamUrl(infoHash,fileIdx),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: startStreamResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as startStreamResponse
}



export type tvStreamsResponse200 = {
  data: Stream[]
  status: 200
}

export type tvStreamsResponseSuccess = (tvStreamsResponse200) & {
  headers: Headers;
};
;

export type tvStreamsResponse = (tvStreamsResponseSuccess)

export const getTvStreamsUrl = (id: number,
    season: number,
    episode: number,) => {




  return `/cinema/api/streams/tv/${id}/${season}/${episode}`
}

export const tvStreams = async (id: number,
    season: number,
    episode: number, options?: RequestInit): Promise<tvStreamsResponse> => {

  const res = await fetch(getTvStreamsUrl(id,season,episode),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: tvStreamsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as tvStreamsResponse
}



export type subtitleCuesResponse200 = {
  data: SubtitleCue[]
  status: 200
}

export type subtitleCuesResponseSuccess = (subtitleCuesResponse200) & {
  headers: Headers;
};
;

export type subtitleCuesResponse = (subtitleCuesResponseSuccess)

export const getSubtitleCuesUrl = (params: SubtitleCuesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/cinema/api/subtitles/cues?${stringifiedParams}` : `/cinema/api/subtitles/cues`
}

export const subtitleCues = async (params: SubtitleCuesParams, options?: RequestInit): Promise<subtitleCuesResponse> => {

  const res = await fetch(getSubtitleCuesUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: subtitleCuesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as subtitleCuesResponse
}



export type movieSubtitlesResponse200 = {
  data: SubtitleTrack[]
  status: 200
}

export type movieSubtitlesResponseSuccess = (movieSubtitlesResponse200) & {
  headers: Headers;
};
;

export type movieSubtitlesResponse = (movieSubtitlesResponseSuccess)

export const getMovieSubtitlesUrl = (id: number,) => {




  return `/cinema/api/subtitles/movie/${id}`
}

export const movieSubtitles = async (id: number, options?: RequestInit): Promise<movieSubtitlesResponse> => {

  const res = await fetch(getMovieSubtitlesUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: movieSubtitlesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as movieSubtitlesResponse
}



export type tvSubtitlesResponse200 = {
  data: SubtitleTrack[]
  status: 200
}

export type tvSubtitlesResponseSuccess = (tvSubtitlesResponse200) & {
  headers: Headers;
};
;

export type tvSubtitlesResponse = (tvSubtitlesResponseSuccess)

export const getTvSubtitlesUrl = (id: number,
    season: number,
    episode: number,) => {




  return `/cinema/api/subtitles/tv/${id}/${season}/${episode}`
}

export const tvSubtitles = async (id: number,
    season: number,
    episode: number, options?: RequestInit): Promise<tvSubtitlesResponse> => {

  const res = await fetch(getTvSubtitlesUrl(id,season,episode),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: tvSubtitlesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as tvSubtitlesResponse
}



export type tvDetailsResponse200 = {
  data: MediaItem
  status: 200
}

export type tvDetailsResponseSuccess = (tvDetailsResponse200) & {
  headers: Headers;
};
;

export type tvDetailsResponse = (tvDetailsResponseSuccess)

export const getTvDetailsUrl = (id: number,) => {




  return `/cinema/api/tv/${id}`
}

export const tvDetails = async (id: number, options?: RequestInit): Promise<tvDetailsResponse> => {

  const res = await fetch(getTvDetailsUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: tvDetailsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as tvDetailsResponse
}
