/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/movie/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["movie_details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tv/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tv_details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Genre: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        Image: {
            file_path: string;
            /** Format: int64 */
            height: number;
            iso_639_1?: string | null;
            /** Format: double */
            vote_average: number;
            /** Format: int64 */
            width: number;
        };
        Images: {
            backdrops: components["schemas"]["Image"][];
            logos: components["schemas"]["Image"][];
            posters: components["schemas"]["Image"][];
        };
        MediaItem: {
            backdrop_path?: string | null;
            genres: components["schemas"]["Genre"][];
            /** Format: int64 */
            id: number;
            images?: null | components["schemas"]["Images"];
            media_type: components["schemas"]["MediaType"];
            overview?: string | null;
            poster_path?: string | null;
            /** Format: double */
            rating?: number | null;
            release_date?: string | null;
            /** Format: int64 */
            runtime?: number | null;
            seasons?: components["schemas"]["Season"][] | null;
            tagline?: string | null;
            title: string;
            videos: components["schemas"]["Video"][];
        };
        /** @enum {string} */
        MediaType: "movie" | "tv";
        SearchResult: {
            backdrop_path?: string | null;
            /** Format: int64 */
            id: number;
            media_type: components["schemas"]["MediaType"];
            overview?: string | null;
            poster_path?: string | null;
            release_date?: string | null;
            title: string;
        };
        Season: {
            air_date?: string | null;
            /** Format: int64 */
            episode_count: number;
            /** Format: int64 */
            id: number;
            name: string;
            poster_path?: string | null;
            /** Format: int64 */
            season_number: number;
        };
        Video: {
            key: string;
            name: string;
            site: string;
            video_type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    movie_details: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaItem"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
        };
    };
    tv_details: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaItem"];
                };
            };
        };
    };
}
