/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * utoipa-axum
 * Utoipa's axum bindings for seamless integration for the two
 * OpenAPI spec version: 0.2.0
 */
export interface Genre {
  id: number;
  name: string;
}

export interface Image {
  file_path: string;
  height: number;
  /** @nullable */
  iso_639_1?: string | null;
  vote_average: number;
  width: number;
}

export interface Images {
  backdrops: Image[];
  logos: Image[];
  posters: Image[];
}

export type MediaType = typeof MediaType[keyof typeof MediaType];


export const MediaType = {
  movie: 'movie',
  tv: 'tv',
} as const;

export interface Season {
  /** @nullable */
  air_date?: string | null;
  episode_count: number;
  id: number;
  name: string;
  /** @nullable */
  poster_path?: string | null;
  season_number: number;
}

export interface Video {
  key: string;
  name: string;
  site: string;
  video_type: string;
}

export interface MediaItem {
  /** @nullable */
  backdrop_path?: string | null;
  genres: Genre[];
  id: number;
  images?: null | Images;
  media_type: MediaType;
  /** @nullable */
  overview?: string | null;
  /** @nullable */
  poster_path?: string | null;
  /** @nullable */
  rating?: number | null;
  /** @nullable */
  release_date?: string | null;
  /** @nullable */
  runtime?: number | null;
  /** @nullable */
  seasons?: Season[] | null;
  /** @nullable */
  tagline?: string | null;
  title: string;
  videos: Video[];
}

export interface SearchResult {
  /** @nullable */
  backdrop_path?: string | null;
  id: number;
  media_type: MediaType;
  /** @nullable */
  overview?: string | null;
  /** @nullable */
  poster_path?: string | null;
  /** @nullable */
  release_date?: string | null;
  title: string;
}

export type SearchParams = {
q: string;
};

export type movieDetailsResponse200 = {
  data: MediaItem
  status: 200
}

export type movieDetailsResponseSuccess = (movieDetailsResponse200) & {
  headers: Headers;
};
;

export type movieDetailsResponse = (movieDetailsResponseSuccess)

export const getMovieDetailsUrl = (id: number,) => {




  return `/movies/api/movie/${id}`
}

export const movieDetails = async (id: number, options?: RequestInit): Promise<movieDetailsResponse> => {

  const res = await fetch(getMovieDetailsUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: movieDetailsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as movieDetailsResponse
}



export type searchResponse200 = {
  data: SearchResult[]
  status: 200
}

export type searchResponseSuccess = (searchResponse200) & {
  headers: Headers;
};
;

export type searchResponse = (searchResponseSuccess)

export const getSearchUrl = (params: SearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/movies/api/search?${stringifiedParams}` : `/movies/api/search`
}

export const search = async (params: SearchParams, options?: RequestInit): Promise<searchResponse> => {

  const res = await fetch(getSearchUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: searchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchResponse
}



export type tvDetailsResponse200 = {
  data: MediaItem
  status: 200
}

export type tvDetailsResponseSuccess = (tvDetailsResponse200) & {
  headers: Headers;
};
;

export type tvDetailsResponse = (tvDetailsResponseSuccess)

export const getTvDetailsUrl = (id: number,) => {




  return `/movies/api/tv/${id}`
}

export const tvDetails = async (id: number, options?: RequestInit): Promise<tvDetailsResponse> => {

  const res = await fetch(getTvDetailsUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: tvDetailsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as tvDetailsResponse
}
